# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(default='General', max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 7, 5, 23, 11, 46, 203143, tzinfo=utc))),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
