# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20170705_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 12, 41, 59, 257860, tzinfo=utc)),
        ),
    ]
