# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 18:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20170706_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Management'), ('3', 'Compensation'), ('4', 'Suggestion'), ('5', 'Complaint')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 18, 42, 36, 831002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(7, message='Too short'), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
