# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 20:10
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20170706_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 20, 10, 10, 893899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=150, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(7, message='Too short'), django.core.validators.MaxLengthValidator(100), feedback.models.validate_allowed_domains]),
        ),
    ]
