# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20170706_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emp_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 20, 19, 55, 859731, tzinfo=utc)),
        ),
    ]
