# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20170706_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 9, 19, 48, 576130, tzinfo=utc)),
        ),
    ]
