# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0002_auto_20170706_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
